### ISSUE TITLE
CentOs support

### ISSUE THREAD

**Issue by docwhat** [poise/poise-ruby#6]
This is just to add an issue so that people can subscribe and be notified when CentOS support is implemented.

The README says (from Jan 2, 2014):

> CentOS 5 and 6 support is coming soon, and possibly Fedora 19.

**Comment by coderanger** [comment]
I'm dropping my packages in favor of system packages and ruby-build. Hopefully someone with more resources than I can step up on making better packages available.

**Comment by docwhat** [comment]
@coderanger So does that mean CentOS support *isn't* being added?  If it is, then can you leave this open until it *is* added?

**Comment by coderanger** [comment]
The whole goal of this cookbook is changing. I don't have the cycles to maintain Ruby builds personally at this point, so I've removed that feature in favor of managing Ruby installs via system packages or ruby-build. It is a module design so if someone else steps forward and is willing to commit the time to maintaining builds, I can add a provider for that easily. At this point CentOS is supported because my custom packages are no longer used.
